before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: BDVg9g3TllGoBrUAkjxFn03hBNLOZ2+upGDoXAYfW4KpE7jHTobCWc+ynHfk4mdCOjLIoNBtJPZVNzDmtDHzBoZVK8ObNG/iQHO9TwaxagXue/Y+09DJv5GbVB3eAVHGxeRJNzaNQt7GH8zeO5FtxJ2lOpgzQ0a+py+bvHogUPOZInYllwo8O+Pi8+fPAv0MYfldyiWUdj+r4LiPM7cHQX9UGa3tpSVw910HlQbITEmDN2otIxm6RIsrZoINeZFoL8I1BKzQzRzOEitCHK/aeYCV4Vptbmnr/5uQzHB6t3ECQnPfOid/TYCwKfOnS4SbETBes3JzGOt+xLTdiexJjhw1+ztusugmuR+Xc2MVNdtD7beMnOZvyTrTiBMhdPfWxwbmTrgQJsNtY3MqwYHIHXEbGsKpChbuAoueu0OzVnGmY9j/HyM3lSRtGzmBNzmU66llComd5OypbiewI0v7iIGcyhekSBNGzNFSPfjlFXCAPFAyjlsxk948Hu/nIgfynVDu42IWzN9kjJ4WploPuNlrG6Kei1rn06qAaUnxSraP6iyDFSat6pTnR5uSCM9aZQERKgSXk/VpLMsTi7AuPYR2W5eYX++sMQ4KMpeqN2O7Cg86m56+mUeDS2u9ukTZ9IEpTpG33TASmkskpEhtbPWeW49UAQcM5nuLD7wPb2Y= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
